[package]
name = "cloudflare_ddns"
version = "0.1.0"
edition = "2021"
authors = ["Luca Lewin <contact@lucalewin.dev>"]
license = "MIT or Apache-2.0"

[dependencies]
serde = { version = "1.0.204", features = ["serde_derive"] }
serde_json = "1.0.120"
ureq = "2.10.0"
